.TH ftrigger 1
.SH NAME
ftrigger \- trigger an action if a file changes
.SH SYNOPSIS
.B ftrigger [-v] @command filename [@command filename...]

.SH DESCRIPTION
.B ftrigger
can watch a list of files and run shell commands if they change.

.B ftrigger
uses the inotify kernel notification mechanism if available, so
it can trigger in real time.  With inotify, ftrigger will trigger when
the file is closed after it was opened for writing.  Without inotify,
this information is not available, so ftrigger might trigger when the
file has only been partially written yet.  Make sure to use proper
atomic file updates (write to a temp file and use rename(3) to move the
new version over the old one when done) to update your files to avoid
race conditions.

.SH EXAMPLES

% ftrigger '@msvc -h sshd' /etc/sshd_config

This will watch /etc/sshd_config, and if it changes, msvc will send a
SIGHUP to the sshd service.

It is also possible to watch more than one file at a time:

% ftrigger '@echo updated' /tmp/a /tmp/b

And it is possible to watch multiple files with different triggers:

% ftrigger '@echo a updated' /tmp/a '@echo b updated' /tmp/b

.SH AUTHOR
minit was written by Felix von Leitner and can be downloaded from
.I http://www.fefe.de/minit/

